baseURL = "https://spicyflavor.vercel.app"
languageCode = "en-us"
title = "Spicyflavor"
theme="archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	customcss = ["css/fix.css"]
	mode="auto"
	useCDN=false
	subtitle = "I'm just trying to build some stuff."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/lechatquivole"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/iAnakinSky"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/athul/"
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Reading List"
url = "/readinglist"
weight = 3

theme="archie"